### ISSUE TITLE
Lisenssi

### ISSUE THREAD

**Issue by Orofil** [akulau/ALO-kurssirepo#2]
Selvitä, millainen lisenssi valitulla ohjelmistolla on. Tämä voi vaikuttaa siihen, miten ohjelmistoa voi käyttää, muokata ja jakaa. Kerro lyhyesti lisenssin ehdot ja rajoitukset.

**Comment by akulau** [comment]
Lisäsin lisenssin tiedot ja megesin omasta haarasta mainiin -> #10
