### ISSUE TITLE
Osallistuminen projektiin

### ISSUE THREAD

**Issue by Orofil** [akulau/ALO-kurssirepo#4]
Selvitä, miten voitte osallistua valitsemaanne projektiin. Tämä voi vaihdella projektista riippuen, mutta yleisesti voitte selvittää seuraavat asiat:
- [x] "Contribution model": Miten projektiin voi osallistua? Onko olemassa tiettyjä rooleja tai vastuita?
- [x] Kuinka tehdä/julkaista muutoksia: Mitä työkaluja ja menettelytapoja tarvitaan ohjelmiston muokkaamiseen ja ehdotusten tekemiseen?

**Comment by akulau** [comment]
Tehty. Mergesin tässä muutokset mainiin -> #11
